Update root-ro
change mount point to userdata

diff --git a/etc/initramfs-tools/scripts/init-bottom/root-ro b/etc/initramfs-tools/scripts/init-bottom/root-ro
--- a/etc/initramfs-tools/scripts/init-bottom/root-ro
+++ b/etc/initramfs-tools/scripts/init-bottom/root-ro
@@ -45,100 +45,100 @@ esac
 # the root fs ${rootmnt} it mounted readonly on the initrams, which fits nicely
 # for our purposes.
 
-modprobe -qb overlay
-if [ $? -ne 0 ]; then
-    log_failure_msg "ERROR 1: missing kernel module overlay"
-    exit 0
-fi
+#modprobe -qb overlay
+#if [ $? -ne 0 ]; then
+#    log_failure_msg "ERROR 1: missing kernel module overlay"
+#    exit 0
+#fi
 
-modprobe -qb fuse
-if [ $? -ne 0 ]; then
-    log_failure_msg "ERROR 2: missing kernel module fuse"
-    exit 0
-fi
+#modprobe -qb fuse
+#if [ $? -ne 0 ]; then
+#    log_failure_msg "ERROR 2: missing kernel module fuse"
+#    exit 0
+#fi
 
 # make the mount point on the init root fs /mnt/root-ro
-[ -d /mnt/root-ro ] || mkdir -p /mnt/root-ro
+[ -d /userdata/root-ro ] || mkdir -p /userdata/root-ro
 if [ $? -ne 0 ]; then
-    log_failure_msg "ERROR 3: failed to create /mnt/root-ro"
+    log_failure_msg "ERROR 3: failed to create /userdata/root-ro"
     exit 0
 fi
 
-# make the mount point on the init root fs /mnt/root-rw
-[ -d /mnt/root-rw ] || mkdir -p /mnt/root-rw
+# make the mount point on the init root fs /userdata/root-rw
+[ -d /userdata/root-rw ] || mkdir -p /userdata/root-rw
 if [ $? -ne 0 ]; then
-    log_failure_msg "ERROR 4: failed to create /mnt/root-rw"
+    log_failure_msg "ERROR 4: failed to create /userdata/root-rw"
     exit 0
 fi
 
-# mount a tmpfs at /mnt/root-rw
-mount -t tmpfs tmpfs /mnt/root-rw
+# mount a tmpfs at /userdata/root-rw
+mount -t tmpfs tmpfs /userdata/root-rw
 if [ $? -ne 0 ]; then
     log_failure_msg "ERROR 5: failed to create tmpfs"
     exit 0
 fi
 
-[ -d /mnt/root-rw/upper ] || mkdir -p /mnt/root-rw/upper
+[ -d /userdata/root-rw/upper ] || mkdir -p /userdata/root-rw/upper
 if [ $? -ne 0 ]; then
-	log_failure_msg "ERROR 6: failed to create /mnt/root-rw/upper"
+	log_failure_msg "ERROR 6: failed to create /userdata/root-rw/upper"
 	exit 0
 fi
 
-[ -d /mnt/root-rw/work ] || mkdir -p /mnt/root-rw/work
+[ -d /userdata/root-rw/work ] || mkdir -p /userdata/root-rw/work
 if [ $? -ne 0 ]; then
-	log_failure_msg "ERROR 7: failed to create /mnt/root-rw/work"
+	log_failure_msg "ERROR 7: failed to create /userdata/root-rw/work"
 	exit 0
 fi
 
-# make the mount point on the init boot fs /mnt/boot-ro
-[ -d /mnt/boot-ro ] || mkdir -p /mnt/boot-ro
+# make the mount point on the init boot fs /userdata/boot-ro
+[ -d /userdata/boot-ro ] || mkdir -p /userdata/boot-ro
 if [ $? -ne 0 ]; then
-    log_failure_msg "ERROR 8: failed to create /mnt/boot-ro"
+    log_failure_msg "ERROR 8: failed to create /userdata/boot-ro"
     exit 0
 fi
 
-# make the mount point on the init boot fs /mnt/boot-ro2
-[ -d /mnt/boot-ro2 ] || mkdir -p /mnt/boot-ro2
+# make the mount point on the init boot fs /userdata/boot-ro2
+[ -d /userdata/boot-ro2 ] || mkdir -p /userdata/boot-ro2
 if [ $? -ne 0 ]; then
-    log_failure_msg "ERROR 9: failed to create /mnt/boot-ro2"
+    log_failure_msg "ERROR 9: failed to create /userdata/boot-ro2"
     exit 0
 fi
 
-# make the mount point on the init boot fs /mnt/boot-rw
-[ -d /mnt/boot-rw ] || mkdir -p /mnt/boot-rw
+# make the mount point on the init boot fs /userdata/boot-rw
+[ -d /userdata/boot-rw ] || mkdir -p /userdata/boot-rw
 if [ $? -ne 0 ]; then
-    log_failure_msg "ERROR 10: failed to create /mnt/boot-rw"
+    log_failure_msg "ERROR 10: failed to create /userdata/boot-rw"
     exit 0
 fi
 
-# mount a tmpfs at /mnt/boot-rw
-mount -t tmpfs tmpfs /mnt/boot-rw
+# mount a tmpfs at /userdata/boot-rw
+mount -t tmpfs tmpfs /userdata/boot-rw
 if [ $? -ne 0 ]; then
     log_failure_msg "ERROR 11: failed to create tmpfs"
     exit 0
 fi
 
-[ -d /mnt/boot-rw/upper ] || mkdir -p /mnt/boot-rw/upper
+[ -d /userdata/boot-rw/upper ] || mkdir -p /userdata/boot-rw/upper
 if [ $? -ne 0 ]; then
-	log_failure_msg "ERROR 12: failed to create /mnt/boot-rw/upper"
+	log_failure_msg "ERROR 12: failed to create /userdata/boot-rw/upper"
 	exit 0
 fi
 
-[ -d /mnt/boot-rw/work ] || mkdir -p /mnt/boot-rw/work
+[ -d /userdata/boot-rw/work ] || mkdir -p /userdata/boot-rw/work
 if [ $? -ne 0 ]; then
-	log_failure_msg "ERROR 13: failed to create /mnt/boot-rw/work"
+	log_failure_msg "ERROR 13: failed to create /userdata/boot-rw/work"
 	exit 0
 fi
 
-# root is mounted on ${rootmnt}, move it to /mnt/root-ro.
-mount -o move ${rootmnt} /mnt/root-ro
+# root is mounted on ${rootmnt}, move it to /userdata/root-ro.
+mount -o move ${rootmnt} /userdata/root-ro
 if [ $? -ne 0 ]; then
-    log_failure_msg "ERROR 14: failed to move root away from ${rootmnt} to /mnt/root-ro"
+    log_failure_msg "ERROR 14: failed to move root away from ${rootmnt} to /userdata/root-ro"
     exit 0
 fi
 
 # mount boot device to /mnt/boot-ro
-BOOTDEV=$(cat /mnt/root-ro/etc/fstab | awk '{if($2=="/boot")print $1}')
+BOOTDEV=$(cat /userdata/root-ro/etc/fstab | awk '{if($2=="/boot")print $1}')
 # check BOOTDEV begins with PARTUUID=
 case "${BOOTDEV}" in
     PARTUUID=*)
@@ -146,16 +146,16 @@ case "${BOOTDEV}" in
         # change BOOTDEV to be /dev/...
         BOOTDEV=`blkid | grep ${PARTUUID} | cut -d: -f1`;;
 esac
-mount -o ro $BOOTDEV /mnt/boot-ro
+mount -o ro $BOOTDEV /userdata/boot-ro
 if [ $? -ne 0 ]; then
-    log_failure_msg "ERROR 15: failed to mount ${BOOTDEV} to /mnt/boot-ro"
+    log_failure_msg "ERROR 15: failed to mount ${BOOTDEV} to /userdata/boot-ro"
     exit 0
 fi
 
-# bindfs /mnt/boot-ro to /mnt/boot-ro2
-bindfs /mnt/boot-ro /mnt/boot-ro2
+# bindfs /userdata/boot-ro to /userdata/boot-ro2
+bindfs /userdata/boot-ro /userdata/boot-ro2
 if [ $? -ne 0 ]; then
-    log_failure_msg "ERROR 16: failed to bindfs /mnt/boot-ro to /mnt/boot-ro2"
+    log_failure_msg "ERROR 16: failed to bindfs /userdata/boot-ro to /userdata/boot-ro2"
     exit 0
 fi
 
@@ -164,77 +164,77 @@ fi
 # "panic". Otherwise the boot process is very likely to fail with even more
 # errors and leave the system in a wired state.
 
-# mount virtual fs ${rootmnt} with rw-fs /mnt/root-rw on top or ro-fs /mnt/root-ro.
-mount -t overlay -o lowerdir=/mnt/root-ro,upperdir=/mnt/root-rw/upper,workdir=/mnt/root-rw/work overlay ${rootmnt}
+# mount virtual fs ${rootmnt} with rw-fs /userdata/root-rw on top or ro-fs /userdata/root-ro.
+mount -t overlay -o lowerdir=/userdata/root-ro,upperdir=/userdata/root-rw/upper,workdir=/userdata/root-rw/work overlay ${rootmnt}
 if [ $? -ne 0 ]; then
     log_failure_msg "ERROR 17: failed to create new ro/rw layer on ${rootmnt}"
     # do recovery and try resoring the mount for ${rootmnt}
-    mount -o move /mnt/root-ro ${rootmnt}
+    mount -o move /userdata/root-ro ${rootmnt}
     if [ $? -ne 0 ]; then
        # thats bad, drop to shell to let the user try fixing this
-       panic "ERROR 18: failed to move /mnt/root-ro back to ${rootmnt}"
+       panic "ERROR 18: failed to move /userdata/root-ro back to ${rootmnt}"
     fi
     exit 0
 fi
 
 # mount virtual fs for boot directory
-mount -t overlay -o lowerdir=/mnt/boot-ro2,upperdir=/mnt/boot-rw/upper,workdir=/mnt/boot-rw/work overlay ${rootmnt}/boot
+mount -t overlay -o lowerdir=/userdata/boot-ro2,upperdir=/userdata/boot-rw/upper,workdir=/userdata/boot-rw/work overlay ${rootmnt}/boot
 if [ $? -ne 0 ]; then
     log_failure_msg "ERROR 19: failed to create new ro/rw layer on ${rootmnt}/boot"
     exit 0
 fi
 
-# now the real root fs is on /mnt/root-ro of the init file system, our layered
+# now the real root fs is on /userdata/root-ro of the init file system, our layered
 # root fs is set up at ${rootmnt}. So we can write anywhere in {rootmnt} and the
 # changes will end up in /mnt/root-rw while /mnt/root-ro it not touched. However
-# /mnt/root-ro and /mnt/root-rw are on the initramfs root fs, which will be removed
-# an replaced by ${rootmnt}. Thus we must move /mnt/root-ro and /mnt/root-rw to the
-# rootfs visible later, ie. ${rootmnt}/mnt/root-ro and ${rootmnt}/mnt/root-rw.
+# /userdata/root-ro and /userdata/root-rw are on the initramfs root fs, which will be removed
+# an replaced by ${rootmnt}. Thus we must move /userdata/root-ro and /userdata/root-rw to the
+# rootfs visible later, ie. ${rootmnt}/userdata/root-ro and ${rootmnt}/userdata/root-rw.
 # Since the layered ro/rw is already up, these changes also end up on
-# /mnt/root-rw while /mnt/root-ro is not touched.
+# /userdata/root-rw while /userdata/root-ro is not touched.
 
-# move mount from /mnt/root-ro to ${rootmnt}/mnt/root-ro
-[ -d ${rootmnt}/mnt/root-ro ] || mkdir -p ${rootmnt}/mnt/root-ro
-mount -o move /mnt/root-ro ${rootmnt}/mnt/root-ro
+# move mount from /userdata/root-ro to ${rootmnt}/userdata/root-ro
+[ -d ${rootmnt}/userdata/root-ro ] || mkdir -p ${rootmnt}/userdata/root-ro
+mount -o move /userdata/root-ro ${rootmnt}/userdata/root-ro
 if [ $? -ne 0 ]; then
-    log_failure_msg "ERROR 20: failed to move /mnt/root-ro to ${rootmnt}/mnt/root-ro"
+    log_failure_msg "ERROR 20: failed to move /userdata/root-ro to ${rootmnt}/userdata/root-ro"
     exit 0
 fi
 
-# move mount from /mnt/root-rw to ${rootmnt}/mnt/root-rw
-[ -d ${rootmnt}/mnt/root-rw ] || mkdir -p ${rootmnt}/mnt/root-rw
-mount -o move /mnt/root-rw ${rootmnt}/mnt/root-rw
+# move mount from /userdata/root-rw to ${rootmnt}/userdata/root-rw
+[ -d ${rootmnt}/userdata/root-rw ] || mkdir -p ${rootmnt}/userdata/root-rw
+mount -o move /userdata/root-rw ${rootmnt}/userdata/root-rw
 if [ $? -ne 0 ]; then
-    log_failure_msg "ERROR 21: failed to move /mnt/root-rw to ${rootmnt}/mnt/root-rw"
+    log_failure_msg "ERROR 21: failed to move /userdata/root-rw to ${rootmnt}/userdata/root-rw"
     exit 0
 fi
 
-# move mount from /mnt/boot-ro to ${rootmnt}/mnt/boot-ro
-[ -d ${rootmnt}/mnt/boot-ro ] || mkdir -p ${rootmnt}/mnt/boot-ro
-mount -o move /mnt/boot-ro ${rootmnt}/mnt/boot-ro
+# move mount from /userdata/boot-ro to ${rootmnt}/userdata/boot-ro
+[ -d ${rootmnt}/userdata/boot-ro ] || mkdir -p ${rootmnt}/userdata/boot-ro
+mount -o move /userdata/boot-ro ${rootmnt}/userdata/boot-ro
 if [ $? -ne 0 ]; then
-    log_failure_msg "ERROR 22: failed to move /mnt/boot-ro to ${rootmnt}/mnt/boot-ro"
+    log_failure_msg "ERROR 22: failed to move /userdata/boot-ro to ${rootmnt}/userdata/boot-ro"
     exit 0
 fi
 
-# move mount from /mnt/boot-ro2 to ${rootmnt}/mnt/boot-ro2
-[ -d ${rootmnt}/mnt/boot-ro2 ] || mkdir -p ${rootmnt}/mnt/boot-ro2
-mount -o move /mnt/boot-ro2 ${rootmnt}/mnt/boot-ro2
+# move mount from /userdata/boot-ro2 to ${rootmnt}/userdata/boot-ro2
+[ -d ${rootmnt}/userdata/boot-ro2 ] || mkdir -p ${rootmnt}/userdata/boot-ro2
+mount -o move /userdata/boot-ro2 ${rootmnt}/userdata/boot-ro2
 if [ $? -ne 0 ]; then
-    log_failure_msg "ERROR 23: failed to move /mnt/boot-ro2 to ${rootmnt}/mnt/boot-ro2"
+    log_failure_msg "ERROR 23: failed to move /userdata/boot-ro2 to ${rootmnt}/userdata/boot-ro2"
     exit 0
 fi
 
-# move mount from /mnt/boot-rw to ${rootmnt}/mnt/boot-rw
-[ -d ${rootmnt}/mnt/boot-rw ] || mkdir -p ${rootmnt}/mnt/boot-rw
-mount -o move /mnt/boot-rw ${rootmnt}/mnt/boot-rw
+# move mount from /userdata/boot-rw to ${rootmnt}/userdata/boot-rw
+[ -d ${rootmnt}/userdata/boot-rw ] || mkdir -p ${rootmnt}/userdata/boot-rw
+mount -o move /userdata/boot-rw ${rootmnt}/userdata/boot-rw
 if [ $? -ne 0 ]; then
-    log_failure_msg "ERROR 24: failed to move /mnt/boot-rw to ${rootmnt}/mnt/boot-rw"
+    log_failure_msg "ERROR 24: failed to move /userdata/boot-rw to ${rootmnt}/userdata/boot-rw"
     exit 0
 fi
 
 # technically, everything is set up nicely now. Since ${rootmnt} had beend
-# mounted read-only on the initfamfs already, ${rootmnt}/mnt/root-ro is it, too.
+# mounted read-only on the initfamfs already, ${rootmnt}/userdata/root-ro is it, too.
 # Now we init process could run - but unfortunately, we may have to prepare
 # some more things here.
 # Basically, there are two ways to deal with the read-only root fs. If the
@@ -245,27 +245,27 @@ fi
 #
 # Let's deal with /etc/fstab first. It usually contains an entry for the root
 # fs, which is no longer valid now. We have to remove it and add our new
-# /mnt/root-ro entry.
+# /userdata/root-ro entry.
 # Remember we are still on the initramfs root fs here, so we have to work on
-# ${rootmnt}/etc/fstab. The original fstab is ${rootmnt}/mnt/root-ro/etc/fstab.
+# ${rootmnt}/etc/fstab. The original fstab is ${rootmnt}/userdata/root-ro/etc/fstab.
 ROOT_TYPE=$(cat /proc/mounts | grep ${ROOT} | cut -d' ' -f3)
 ROOT_OPTIONS=$(cat /proc/mounts | grep ${ROOT} | cut -d' ' -f4)
 BOOT_TYPE=$(cat /proc/mounts | grep ${BOOTDEV} | cut -d' ' -f3)
 BOOT_OPTIONS=$(cat /proc/mounts | grep ${BOOTDEV} | cut -d' ' -f4)
 cat <<EOF >${rootmnt}/etc/fstab
 #
-#  This fstab is in RAM, the real one can be found at /mnt/root-ro/etc/fstab
+#  This fstab is in RAM, the real one can be found at /userdata/root-ro/etc/fstab
 #  The original entry for '/' and all swap files have been removed.  The new
 #  entry for the read-only the real root fs follows. Write access can be
 #  enabled using:
-#    sudo mount -o remount,rw /mnt/root-ro
+#    sudo mount -o remount,rw /userdata/root-ro
 #  re-mounting it read-only is done using:
-#    sudo mount -o remount,ro /mnt/root-ro
+#    sudo mount -o remount,ro /userdata/root-ro
 #
-${BOOTDEV} /mnt/boot-ro ${BOOT_TYPE} ${BOOT_OPTIONS} 0 0
-${ROOT} /mnt/root-ro ${ROOT_TYPE} ${ROOT_OPTIONS} 0 0
+${BOOTDEV} /userdata/boot-ro ${BOOT_TYPE} ${BOOT_OPTIONS} 0 0
+${ROOT} /userdata/root-ro ${ROOT_TYPE} ${ROOT_OPTIONS} 0 0
 #
-#  remaining entries from the original /mnt/root-ro/etc/fstab follow.
+#  remaining entries from the original /userdata/root-ro/etc/fstab follow.
 #
 EOF
 if [ $? -ne 0 ]; then
@@ -274,7 +274,7 @@ if [ $? -ne 0 ]; then
 fi
 
 #remove root, boot and swap from fstab
-cat ${rootmnt}/mnt/root-ro/etc/fstab | awk '{if($2!="/"&&$2!="/boot"&&$2!="swap")print $0}' >> ${rootmnt}/etc/fstab
+cat ${rootmnt}/userdata/root-ro/etc/fstab | awk '{if($2!="/"&&$2!="/boot"&&$2!="swap")print $0}' >> ${rootmnt}/etc/fstab
 if [ $? -ne 0 ]; then
     log_failure_msg "ERROR 26: failed to modify etc/fstab (step 2)"
     #exit 0
